import { useState } from "react";
import { datasetFields, processingVerdict, reviewText, testTeamApproval, TEST_TEAM_APPROVAL_OPTIONS } from "../lib/datasetReview";

export default function OverviewPanel({ datasets, onLoad, currentDataset, currentReview, dies = [], excludedIds = [] }) {
  const [project, setProject] = useState("");
  const [status, setStatus] = useState("");
  const [approvalFilter, setApprovalFilter] = useState("");
  const projects = [...new Set(datasets.map((d) => d.projectName || d.display?.projectName).filter(Boolean))].sort();
  const rows = datasets.filter((d) => !project || (d.projectName || d.display?.projectName) === project).map((d) => ({ dataset: d, verdict: processingVerdict(d.analyticsReview) })).filter((d) => (!status || d.verdict.label === status) && (!approvalFilter || testTeamApproval(d.dataset).label === approvalFilter));
  return <section className="library-stack"><article className="analysis-card"><div className="analysis-card-head"><div><h2>Overview</h2><p>A cleanroom view of measurement acceptance and wafer and die processing results.</p></div></div>
    <p>Measurement acceptance is the test team’s decision across all applicable measurements. Propagation fit quality checks the MSE of included dies: Meets fit criteria when all included fits qualify, Needs fit review when any are unusable or exceed the threshold, and Not evaluated when no saved review is available.</p>
    <div className="review-edit-grid"><label className="mapping-field"><span>Overview project</span><select value={project} onChange={(e) => setProject(e.target.value)}><option value="">All projects</option>{projects.map((p) => <option key={p}>{p}</option>)}</select></label><label className="mapping-field"><span>Propagation fit quality</span><select value={status} onChange={(e) => setStatus(e.target.value)}><option value="">All results</option>{["Meets fit criteria", "Needs fit review", "Not evaluated"].map((s) => <option key={s}>{s}</option>)}</select></label><label className="mapping-field"><span>Measurement acceptance filter</span><select aria-label="Measurement acceptance filter" value={approvalFilter} onChange={(e) => setApprovalFilter(e.target.value)}><option value="">All decisions</option>{TEST_TEAM_APPROVAL_OPTIONS.map((s) => <option key={s}>{s}</option>)}</select></label></div>
    <div className="overview-wafer-grid">{rows.map(({ dataset: d, verdict: v }) => { const f = datasetFields(d); const approval = testTeamApproval(d); return <article className="help-card" key={d.overviewKey}><p>Measurement acceptance</p><strong className={`review-verdict ${approval.tone}`}>{approval.label}</strong><p>Propagation fit quality: <strong className={`review-verdict ${v.tone}`}>{v.label}</strong></p><h3>{d.projectName || d.display?.projectName} · {f.slot}</h3><p>{f.platform} · {f.step} · {f.bb}</p><p>{reviewText(d, "stepDescription") || "Step description not recorded"}</p><p>{v.total ? `${v.passed}/${v.total} included dies meet fit criteria` : "Load and review this dataset to assess it."}</p><p><strong>Test team:</strong> {reviewText(d, "testTeamComments") || "No comments recorded"}</p><button type="button" onClick={() => onLoad(d)}>Inspect dataset</button></article>; })}</div>
    {!rows.length ? <p>No datasets match these filters.</p> : null}
  </article>{currentDataset ? <article className="analysis-card"><h2>Active wafer · {currentDataset.projectName} · {datasetFields(currentDataset).slot}</h2><p><strong className={`review-verdict ${processingVerdict(currentReview).tone}`}>{processingVerdict(currentReview).label}</strong> Live propagation fit results; save and publish a review to share them.</p><div className="overview-die-grid">{dies.map((die) => { const excluded = excludedIds.includes(String(die.chipId)); const pass = die.passMse && die.lossDbPerCm !== null; return <div className={`overview-die ${excluded ? "pending" : pass ? "pass" : "fail"}`} key={die.chipId}><strong>Die {die.chipId}</strong><span>{excluded ? "Excluded" : pass ? "Pass" : "Fail"}</span></div>; })}</div></article> : null}</section>;
}
